version: "3.8"

services:
  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bestteamever
      MYSQL_USER: cs5330
      MYSQL_PASSWORD: Sql5330!
      MYSQL_DATABASE: dbproj
    # ports:
    #   - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
    networks:
      - cs5330_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    networks:
      - cs5330_network
    image: cs5330-frontend:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    networks:
      - cs5330_network
    image: cs5330-backend:latest

networks:
  cs5330_network:
    driver: bridge
