version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bestteamever
      MYSQL_USER: cs5330
      MYSQL_PASSWORD: Sql5330!
      MYSQL_DATABASE: dbproj
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
